kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-a
  namespace: mongo
spec:
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      failure-domain.beta.kubernetes.io/zone: eu-west-1a
  resources:
    requests:
      storage: 18Gi
