apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-a
  namespace: mongo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: mongo
        zone: eu-west-1a
    spec:
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: eu-west-1a
      hostname: mongo-a
      containers:
      - name: mongo
        image: mongo:3.2.8
        args:
        - --replSet
        - rs0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1024Mi
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongo-a
