apiVersion: v1
kind: Pod
metadata:
  name: mongo-mon
  namespace: mongo
spec:
  containers:
  - name: mongo
    image: mongo:3.2.8
    command:
    - /bin/bash
    - -c
    - 'while true; do clear; for i in "" -a -b -c; do echo -n "mongo$i status: "; mongo --host mongo$i --quiet --eval "{ping: 1}"; done; sleep 1; done'
    env:
    - name: TERM
      value: xterm
